{{- if and (not .Values.llm.existingSecret) .Values.llm.apiKey -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ziro.fullname" . }}-llm
  labels: {{- include "ziro.labels" . | nindent 4 }}
type: Opaque
stringData:
  LLM_API_KEY: {{ .Values.llm.apiKey | quote }}
{{- end }}
