"""Reproduce Script Generator — creates standalone scripts to reproduce findings.

Generates Python and shell scripts that demonstrate each vulnerability
without requiring ziro. Useful for client verification and reporting.
"""

import logging
import textwrap
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)


def generate_reproduce_script(
    vulnerability_reports: list[dict[str, Any]],
    output_dir: Path,
    format: str = "python",
) -> Path | None:
    """Generate a standalone reproduce script for all findings.

    Args:
        vulnerability_reports: List of vulnerability report dicts from tracer.
        output_dir: Directory to write the script to.
        format: "python" or "shell".

    Returns:
        Path to the generated script, or None if no reproducible findings.
    """
    reproducible = [r for r in vulnerability_reports if r.get("poc_script_code")]
    if not reproducible:
        logger.info("No reproducible findings to generate script for")
        return None

    if format == "python":
        return _generate_python_script(reproducible, output_dir)
    elif format == "shell":
        return _generate_shell_script(reproducible, output_dir)
    else:
        logger.warning("Unknown format: %s", format)
        return None


def _generate_python_script(
    findings: list[dict[str, Any]],
    output_dir: Path,
) -> Path:
    """Generate a Python reproduce script."""
    output_dir.mkdir(parents=True, exist_ok=True)
    script_path = output_dir / "reproduce.py"

    header = textwrap.dedent(f"""\
        #!/usr/bin/env python3
        \"\"\"Vulnerability Reproduction Script

        Generated by Ziro on {datetime.now(UTC).strftime('%Y-%m-%d %H:%M:%S UTC')}

        This script reproduces {len(findings)} vulnerability finding(s).
        Run each test independently to verify the vulnerability still exists.

        Requirements: pip install requests
        \"\"\"

        import sys
        import requests
        from urllib.parse import urljoin

        # Disable SSL warnings for testing
        import urllib3
        urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

        TIMEOUT = 10
        VERIFY_SSL = False


        def banner(vuln_id: str, title: str, severity: str) -> None:
            print(f"\\n{'='*60}")
            print(f"  {{vuln_id}} | {{severity.upper()}} | {{title}}")
            print(f"{'='*60}")


        def result(success: bool, detail: str = "") -> None:
            status = "VULNERABLE" if success else "NOT VULNERABLE"
            color = "\\033[91m" if success else "\\033[92m"
            print(f"  {{color}}[{{status}}]\\033[0m {{detail}}")

    """)

    test_functions = []
    for i, finding in enumerate(findings, 1):
        func_name = f"test_{i}_{_sanitize_name(finding.get('title', 'unknown'))}"
        vuln_id = finding.get("id", f"vuln-{i:04d}")
        title = finding.get("title", "Unknown")
        severity = finding.get("severity", "unknown")
        target = finding.get("target", "")
        endpoint = finding.get("endpoint", "")
        method = finding.get("method", "GET").upper()
        poc_code = finding.get("poc_script_code", "")
        description = finding.get("description", "")

        func = textwrap.dedent(f"""\
            def {func_name}() -> bool:
                \"\"\"
                {title}
                Severity: {severity.upper()}
                Target: {target}
                {description[:200] if description else ''}
                \"\"\"
                banner("{vuln_id}", "{_escape(title)}", "{severity}")
                try:
        """)

        # If poc_code looks like a curl/command, wrap it
        if poc_code.strip().startswith("curl ") or poc_code.strip().startswith("wget "):
            func += _wrap_curl_as_requests(poc_code, target, endpoint, method)
        else:
            # Include the PoC code directly, indented
            for line in poc_code.strip().splitlines():
                func += f"            {line}\n"
            func += f'            result(True, "PoC executed — verify output above")\n'
            func += "            return True\n"

        func += textwrap.dedent("""\
                except requests.RequestException as e:
                    result(False, f"Request failed: {e}")
                    return False
                except Exception as e:
                    result(False, f"Error: {e}")
                    return False
        """)

        test_functions.append((func_name, func))

    # Main function
    main = "\ndef main() -> None:\n"
    main += '    print("\\n\\033[1mZiro Vulnerability Reproduction Script\\033[0m")\n'
    main += f'    print("Findings: {len(findings)}")\n'
    main += "    results = []\n\n"

    for func_name, _ in test_functions:
        main += f"    results.append((\"{func_name}\", {func_name}()))\n"

    main += textwrap.dedent("""
        print(f"\\n{'='*60}")
        print(f"  SUMMARY: {sum(1 for _, r in results if r)}/{len(results)} vulnerabilities confirmed")
        print(f"{'='*60}")

        sys.exit(0 if not any(r for _, r in results) else 1)


    if __name__ == "__main__":
        main()
    """)

    content = header
    for _, func in test_functions:
        content += "\n" + func
    content += main

    script_path.write_text(content, encoding="utf-8")
    logger.info("Generated reproduce script: %s (%d findings)", script_path, len(findings))
    return script_path


def _generate_shell_script(
    findings: list[dict[str, Any]],
    output_dir: Path,
) -> Path:
    """Generate a shell reproduce script."""
    output_dir.mkdir(parents=True, exist_ok=True)
    script_path = output_dir / "reproduce.sh"

    lines = [
        "#!/bin/bash",
        f"# Vulnerability Reproduction Script",
        f"# Generated by Ziro on {datetime.now(UTC).strftime('%Y-%m-%d %H:%M:%S UTC')}",
        f"# Findings: {len(findings)}",
        "",
        'RED="\\033[91m"',
        'GREEN="\\033[92m"',
        'BOLD="\\033[1m"',
        'RESET="\\033[0m"',
        "",
        "PASS=0",
        "FAIL=0",
        "",
    ]

    for i, finding in enumerate(findings, 1):
        vuln_id = finding.get("id", f"vuln-{i:04d}")
        title = finding.get("title", "Unknown")
        severity = finding.get("severity", "unknown").upper()
        poc_code = finding.get("poc_script_code", "")

        lines.append(f'echo ""')
        lines.append(f'echo "============================================================"')
        lines.append(f'echo "  {vuln_id} | {severity} | {_escape_shell(title)}"')
        lines.append(f'echo "============================================================"')
        lines.append("")

        # Include PoC code
        for line in poc_code.strip().splitlines():
            lines.append(line)

        lines.append("")
        lines.append("if [ $? -eq 0 ]; then")
        lines.append(f'    echo -e "${{RED}}[VULNERABLE]${{RESET}} {_escape_shell(title)}"')
        lines.append("    FAIL=$((FAIL+1))")
        lines.append("else")
        lines.append(f'    echo -e "${{GREEN}}[NOT VULNERABLE]${{RESET}} {_escape_shell(title)}"')
        lines.append("    PASS=$((PASS+1))")
        lines.append("fi")
        lines.append("")

    lines.extend([
        'echo ""',
        'echo "============================================================"',
        'echo "  SUMMARY: $FAIL vulnerable, $PASS clean"',
        'echo "============================================================"',
        "",
        "exit $FAIL",
    ])

    script_path.write_text("\n".join(lines), encoding="utf-8")
    logger.info("Generated shell reproduce script: %s (%d findings)", script_path, len(findings))
    return script_path


def _sanitize_name(name: str) -> str:
    """Convert a title to a valid Python function name."""
    import re
    name = re.sub(r"[^a-zA-Z0-9]+", "_", name.lower())
    name = name.strip("_")[:40]
    return name or "unknown"


def _escape(s: str) -> str:
    """Escape string for Python string literal."""
    return s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")


def _escape_shell(s: str) -> str:
    """Escape string for shell."""
    return s.replace("'", "'\\''").replace('"', '\\"')


def _wrap_curl_as_requests(poc_code: str, target: str, endpoint: str, method: str) -> str:
    """Convert a curl-like PoC into requests-based Python code."""
    return textwrap.dedent(f"""\
            url = "{target}{endpoint}"
            # Original PoC: {poc_code.strip()[:100]}
            response = requests.request(
                "{method}",
                url,
                timeout=TIMEOUT,
                verify=VERIFY_SSL,
            )
            if response.status_code == 200:
                result(True, f"Status {{response.status_code}}, Length {{len(response.text)}}")
                return True
            else:
                result(False, f"Status {{response.status_code}}")
                return False
    """)
